name: Docker

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Build Kavita
        run: ./docker-build.sh
      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kavita
          registry: ghcr.io
          username: TorchedSammy
          password: ${{ secrets.GITHUB_TOKEN }}
